[~] {@20124} Total refactoring, more pretty dropdown vertical menu
cscart/cscart-boilerplate pull request #100
Opened 2017-11-23 10:20 UTC by kugimiya

2017-11-24 05:59 UTC, torunar requested changes

2017-11-24 05:59 UTC, torunar commented on templates/blocks/categories/categories_dropdown_vertical.tpl
> +<style>
Воу-воу, палехчи, гардемарин. Стилям место в файлах стилей.

2017-11-24 05:59 UTC, torunar commented on templates/blocks/categories/categories_dropdown_vertical.tpl
> +            {assign var="unique_elm_id" value="topmenu_`$block.block_id`_`$unique_elm_id`"}
У нас уже давно smarty3, в нем можно писать
```tpl
{$foo = "bar"|baz}
```

2017-11-24 05:59 UTC, torunar commented on templates/blocks/categories/categories_dropdown_vertical.tpl
> +        {foreach from=$items item="item1" name="item1"}
http://docs.cs-cart.com/4.6.x/developer_guide/core/coding_standards/php.html#names-of-variables-array-keys-and-class-properties
```tpl
{foreach $items as $item_level_1}
```

2017-11-24 05:59 UTC, torunar commented on templates/blocks/categories/categories_dropdown_vertical.tpl
> +                            {foreach from=$item1.$childs item="item2" name="item2"}
```tpl
{foreach $item_level_1.childs as $item_level_2}
```

2017-11-24 13:55 UTC, torunar approved these changes

2017-11-29 09:14 UTC, torunar requested changes

2017-11-29 09:14 UTC, torunar commented on templates/blocks/menu/dropdown_vertical.tpl
> +            {$unique_elm_child_id = "topmenu_`$block.block_id`_`$unique_elm_id`_child"}
🙀 
Просто юзай `uniqid`, зачем тебе md5 от URL и случаное значение в диапазоне 0–1500?

2017-11-29 09:53 UTC, kugimiya commented on templates/blocks/menu/dropdown_vertical.tpl
> +            {$unique_elm_child_id = "topmenu_`$block.block_id`_`$unique_elm_id`_child"}
Беда в том, что имея в массиве несколько одинаковых нод (например корневую директорию "Все страницы", и корневую директорию "Категорий", и ноды одного и того же элемента будут и там и тут), мы получим конфликт. Так, например, dropdown'ы будут тоглиться и там и тут сразу.
`uniqid` это функция, которая сгененирует случайную последовательность чаров? :3

2017-11-29 10:07 UTC, torunar commented on templates/blocks/menu/dropdown_vertical.tpl
> +            {$unique_elm_child_id = "topmenu_`$block.block_id`_`$unique_elm_id`_child"}
@kugimiya http://php.net/manual/ru/function.uniqid.php

2017-11-29 13:59 UTC, torunar approved these changes

2017-11-29 14:26 UTC, bzzeke commented on templates/blocks/menu/dropdown_vertical.tpl
> +            {$unique_elm_child_id = "topmenu_`$block.block_id`_`$unique_elm_id`_child"}
вообще грешно такой хренью в темплейтах заниматься

2017-11-30 07:42 UTC, torunar approved these changes

2017-11-30 12:22 UTC, torunar approved these changes

2017-12-01 08:17 UTC, torunar requested changes

2017-12-01 08:17 UTC, torunar commented on css/styles.less
> +    p.caret {
`p.caret` используется только в https://github.com/cscart/cscart-boilerplate/pull/100/commits/94c46f444607762f79a33fd091c8a8ef100d4266#diff-74aa5b869574415357887c04ee3807d6R59, в остальных местах — `span.caret`.
Может, юзать просто класс в качестве селектора?

2017-12-01 08:17 UTC, torunar commented on js/core.js
> +
```javascript
var isDropdown = e.target.className == 'caret' || e.target.lastChild.className = 'caret';
```
?

2017-12-01 08:17 UTC, torunar commented on js/core.js
> +                    if ( (e.target.nodeName != "SPAN") && isDropdown) {
Не лучше ли обернуть название элемента меню не в простой span, а с классом типа `.menu-item__name` и отталкиваться в скрипте от наличия класса? Это читаемость кода улучшит, т.к. будет ясна мотивация:

```Происходит X, потому что Y — это не элемент с названием меню```
vs
```Происходит X, потому что Y — это не span```

2017-12-01 08:17 UTC, torunar commented on js/core.js
> +            // Accordeon vertical menu: Prevent relocation if click target is not span
accordion

2017-12-01 09:14 UTC, torunar approved these changes

2017-12-01 11:58 UTC, merged